"""Fixed relationship with balsts, contacts, and blast recipients

Revision ID: c77a55eab0a0
Revises: eb4bddb2d5b7
Create Date: 2024-09-30 00:56:30.839076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77a55eab0a0'
down_revision: Union[str, None] = 'eb4bddb2d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
