"""Fix BlastRecipient relationships

Revision ID: eb4bddb2d5b7
Revises: f3dac247265d
Create Date: 2024-09-30 00:42:28.972395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4bddb2d5b7'
down_revision: Union[str, None] = 'f3dac247265d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
